# -*- coding: utf-8 -*-
"""twitter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ULmGigqx_6oJlJm0z8BDni_0OEr5OCQg
"""

pip install tweepy

import tweepy

def access_keys():

    twitter_auth_keys={
        "api_key" : "",        
        "api_secret" : "",
        "access_token" : "",
        "access_token_secret" : "",
    }  #integrating twitter app with ours

    return twitter_auth_keys

def index():

    twitter_func=access_keys()
   

    auth=tweepy.OAuthHandler(
        twitter_func['api_key'],
        twitter_func['api_secret']
    )

    auth.set_access_token(
        twitter_func['access_token'],
        twitter_func['access_token_secret']
    )
    api=tweepy.API(auth, wait_on_rate_limit=True)  

    return api

def tweet_something(text):
    api=index()
    status=api.update_status(status=text)

def retweet_something(id_post):
    api=index()
    api.retweet(id_post)

def check_followers(screen_name):
    api=index()
    for user in tweepy.Cursor(api.followers, screen_name=screen_name).items():
        print(user.screen_name)

def check_following(screen_name):
    api=index()
    for friend in api.friends(screen_name=screen_name):
        print(friend.screen_name) 
    
#latest trends

def trendy():
    api=index()
    trends=api.trends_place(1)
    for i in trends[0]['trends']:
        print(i['name'])

def search_query(query_name,counts):
    api=index()
    for tweet in api.search(q=query_name,count=count):
        print(tweet)


def like_tweet(id):
    api=index()
    api.create_favorite(id)

def querybased_data(query,numbers):
    api=index()
    tweets=tweepy.Cursor(api.search,q=query).items(number)
    for tweet in tweets:
        print(tweet.user.screen_name)
        print(tweet.text)
        

def follow_user(screen_name):
    api=index()
    try:

        api.create_friendship(username)
        print("Friendship created")
    except:
        print('Username doest exist')

for i in range(5):
    tweet_something(f'automating python script {i+1}')

